### PR TITLE
Fix #36 - be sure the total is still an int

### LINKED ISSUE #36: Tests fail on i386
https://salsa.debian.org/phpmyadmin-team/motranslator/-/jobs/1168052#L1509
```
1) PhpMyAdmin\MoTranslator\Tests\MoFilesTest::testEmptyMoFile with data set #4 ('./tests/data/error/fpdle.mo')
TypeError: Argument 3 passed to PhpMyAdmin\MoTranslator\StringReader::readintarray() must be of the type int,
 float given, called in src/Translator.php on line 140
```
https://github.com/phpmyadmin/motranslator/blob/392db58917e16216270d7821e62cd5393287439f/src/Translator.php#L140
https://github.com/phpmyadmin/motranslator/blob/392db58917e16216270d7821e62cd5393287439f/src/StringReader.php#L101

### PR DESCRIPTION
**Pull request by williamdes**
Fixes: #36

### CODE REVIEW

File: src/Translator.php [hunk 1]
```diff
@@ -148,13 +148,17 @@ private function loadTranslationsFromFile(string $filename): void
             $translations = $stream->readint($unpack, 16);
 
             /* get original and translations tables */
-            $tableOriginals = $stream->readintarray($unpack, $originals, $total * 2);
-            $tableTranslations = $stream->readintarray($unpack, $translations, $total * 2);
+            $totalTimeTwo = (int) ($total * 2);// Fix for issue #36 on ARM
```
Comment (williamdes) [inline src/Translator.php]: The fix

**Comment by williamdes** [comment]
@mauriciofauth If you agree on this one I can merge all the PRs and be ready for a new minor version.
@ibennetch Does it seem okay for you ?

**Review by MauricioFauth — APPROVED** [review]

File: src/Translator.php (hunk 1 above)
Comment (ibennetch) [reply src/Translator.php:151]: Do you want to call this totalTimesTwo? Usually "times" with an "s" is used for multiplication so that might be better than "time".

Otherwise looks good to me. Nice work tracking this down.

**Review by ibennetch — APPROVED** [review]

File: src/Translator.php (hunk 1 above)
Comment (ibennetch) [inline src/Translator.php]: Do you want to call this totalTimesTwo? Usually "times" with an "s" is used for multiplication so that might be better than "time".

Otherwise looks good to me. Nice work tracking this down.

**Review by ibennetch — APPROVED** [review]

File: src/Translator.php (hunk 1 above)
Comment (williamdes) [reply src/Translator.php]: Sure, good catch
